### ISSUE TITLE
Sql not applicable to Mysql or ODPS

### ISSUE THREAD

**Issue by aso233** [defog-ai/sqlcoder#109]
The generated SQL statement is not applicable to MySQL or ODPS if it contains statements with functions such as date_trunc, date_part, and CURRENT_DATE. These seem to be PostgreSQL functions.

Is there any way to generate SQL statements for a specific database type in the model?

**Comment by aso233** [comment]
I have tried to prompt the model like this: 

The generated SQL statement must follow the MySQL syntax specification. Do not use method like: date_trunc、date_part、CURRENT_DATE

But it doesn't works.

**Comment by JennieGao-njust** [comment]
> I have tried to prompt the model like this:
> 
> The generated SQL statement must follow the MySQL syntax specification. Do not use method like: date_trunc、date_part、CURRENT_DATE
> 
> But it doesn't works.
I encountered the same problem, have you solved it?

**Comment by FaizelK** [comment]
@aso233 we have been asking from 2023 but I think the guys are not focused on opensource anymore, see this link I am refering to

[https://github.com/defog-ai/sqlcoder/issues/11](https://github.com/defog-ai/sqlcoder/issues/11)
