### ISSUE TITLE
How to generate SQL for MySQL?

### ISSUE THREAD

**Issue by ricosr** [defog-ai/sqlcoder#11]
I find it can generate SQL for PostgreSQL exactly, how can I use it to generate SQL for MySQL? Thank you!

**Comment by rishsriv** [comment]
Hi there, we have not yet open-sourced our MySQL fine-tuned model, but hope to do that in the next month. I'll update you here once that's done!

**Comment by ricosr** [comment]
> Hi there, we have not yet open-sourced our MySQL fine-tuned model, but hope to do that in the next month. I'll update you here once that's done!

Great to hear this message, thanks for your great work!

**Comment by buddyroo30** [comment]
Any update on this? When do you think you'll be releasing the model that supports MySQL? Thanks.

**Comment by rishsriv** [comment]
Hi there, we are hoping to do it this month or early next month – depending on when we find a bit of breathing room to focus on the open-source model. We have a tiny 4-person engineering team, and are prioritizing commercial inbounds at the moment :) But hope to release it in the next 2-6 weeks!

**Comment by Kshitizkhandel** [comment]
@buddyroo30 @rishsriv  Do you happen to know how we could convert these Postgres queries to Mariadb Queries? I came across sqlglot that transpiles into different dialects but it doesn't support Mariadb

**Comment by FaizelK** [comment]
@rishsriv any feedback on this?
