### ISSUE TITLE
[疑惑] 生成的SQL 总是会有一些额外的 信息

### ISSUE THREAD

**Issue by suiquantong** [defog-ai/sqlcoder#112]
亲爱的作者您好，我是您忠实的中国粉丝，希望能使用你们的大模型，来完成SQL的生成工作，
但是在使用sqlcoder-8b时遇到了很多问题，其中最让我苦恼的就是 每次提问 生成sql后会有很多其他信息返回给我，你能帮我解决这个故障吗？

![image](https://github.com/defog-ai/sqlcoder/assets/37520861/91808919-82d2-47b4-9499-d0a9acddff61)

还有一个问题，我想知道什么样的数据表结构 可以被模型理解到

**Comment by chuangzhidan** [comment]
me2，many redundant clauses ,always use tabel alisas like d., t., s.

**Comment by suiquantong** [comment]
我不明白你的意思
