### ISSUE TITLE
The inference time of the model is very unstable.

### ISSUE THREAD

**Issue by yohohohoho** [defog-ai/sqlcoder#14]
The effect of this project is very good, but the inference time of the model is very unstable. Sometimes it only takes 2ms, and sometimes it takes more than 100ms.  Is it because I am using the wrong method?

**Comment by rishsriv** [comment]
Hi there! What hardware are you using for inference? Inference time generally depends on the number of tokens generated. So the model generates a simple query (like `SELECT COUNT(*) from users;`), inference time will be very fast

But if it generates a more complex query, like the one below, inference time will be much slower

```sql
WITH new_york_revenue AS (
  SELECT sum(sales.price * sales.quantity) AS revenue
  FROM   sales
  JOIN   customers on sales.customer_id = customers.customer_id
  JOIN   salespeople on sales.salesperson_id = salespeople.salesperson_id
  WHERE  customers.address like '%New York%'
     and salespeople.region = 'North America'
), san_francisco_revenue AS (
  SELECT sum(sales.price * sales.quantity) AS revenue
  FROM   sales
  JOIN   customers on sales.customer_id = customers.customer_id
  JOIN   salespeople on sales.salesperson_id = salespeople.salesperson_id
  WHERE  customers.address like '%San Francisco%'
     and salespeople.region = 'North America'
)
SELECT new_york_revenue.revenue AS new_york_revenue,
       san_francisco_revenue.revenue AS san_francisco_revenue,
       new_york_revenue.revenue - san_francisco_revenue.revenue AS difference
FROM   new_york_revenue, san_francisco_revenue;
```

**Comment by yohohohoho** [comment]
> Hi there! What hardware are you using for inference? Inference time generally depends on the number of tokens generated. So the model generates a simple query (like `SELECT COUNT(*) from users;`), inference time will be very fast
> 
> But if it generates a more complex query, like the one below, inference time will be much slower
> 
> ```sql
> WITH new_york_revenue AS (
>   SELECT sum(sales.price * sales.quantity) AS revenue
>   FROM   sales
>   JOIN   customers on sales.customer_id = customers.customer_id
>   JOIN   salespeople on sales.salesperson_id = salespeople.salesperson_id
>   WHERE  customers.address like '%New York%'
>      and salespeople.region = 'North America'
> ), san_francisco_revenue AS (
>   SELECT sum(sales.price * sales.quantity) AS revenue
>   FROM   sales
>   JOIN   customers on sales.customer_id = customers.customer_id
>   JOIN   salespeople on sales.salesperson_id = salespeople.salesperson_id
>   WHERE  customers.address like '%San Francisco%'
>      and salespeople.region = 'North America'
> )
> SELECT new_york_revenue.revenue AS new_york_revenue,
>        san_francisco_revenue.revenue AS san_francisco_revenue,
>        new_york_revenue.revenue - san_francisco_revenue.revenue AS difference
> FROM   new_york_revenue, san_francisco_revenue;
> ```



Thank you for your response, this is the problem I encountered, in the case of output with almost the same length in the two sections below, the time consumption is five times greater.
`time:6.521226406097412
SELECT water_outage_info.id,
       water_outage_info.incident_address
FROM   water_outage_info
WHERE  water_outage_info.id = (SELECT max(water_outage_info.id)
                               FROM   water_outage_info);
`

`time:32.622504472732544
SELECT water_outage_info.outage_reason,
       count(*) AS count
FROM   water_outage_info
GROUP BY water_outage_info.outage_reason
ORDER BY count(*) DESC;
`

**Comment by bigmancomeon** [comment]
Why  your model run  so fast? What gpu do you use and how much gpu memory do you use?
