### ISSUE TITLE
Could you upload the INT4 quantization and INT8 quantization model to the huggingface

### ISSUE THREAD

**Issue by robinji0** [defog-ai/sqlcoder#19]
Could you upload the INT4 quantization and INT8 quantization model to the huggingface

**Comment by robinji0** [comment]
Could you upload the INT4 quantization and INT8 quantization model to the huggingface please?  Just like ChatGLM here https://huggingface.co/THUDM/chatglm-6b-int4 . 
Since load the INT4 quantization model need to load the original model first, and it needs large memory which cannot run in our local machine successfully. So could you upload the INT4 quantization or INT8 quantization result of the sqlcoder to the huggingface please? The request is very strong, please 🥺

**Comment by xwdreamer** [comment]
@robinji0 Does this sqlcoder model support Chinese question？

**Comment by robinji0** [comment]
> @robinji0 Does this sqlcoder model support Chinese question？

Yes, it does. But it's very slow.

**Comment by 12210122** [comment]
> Could you upload the INT4 quantization and INT8 quantization model to the huggingface please? Just like ChatGLM here https://huggingface.co/THUDM/chatglm-6b-int4 . Since load the INT4 quantization model need to load the original model first, and it needs large memory which cannot run in our local machine successfully. So could you upload the INT4 quantization or INT8 quantization result of the sqlcoder to the huggingface please? This request is very strong, please 🥺

已经有了，就在这几天。这个是34B的GPTQ版本，实测加载之后18G显存。此外还有AWQ版本。
TheBloke/sqlcoder-34b-alpha-GPTQ

**Comment by lozzo** [comment]
> > Could you upload the INT4 quantization and INT8 quantization model to the huggingface please? Just like ChatGLM here [huggingface.co/THUDM/chatglm-6b-int4](https://huggingface.co/THUDM/chatglm-6b-int4) . Since load the INT4 quantization model need to load the original model first, and it needs large memory which cannot run in our local machine successfully. So could you upload the INT4 quantization or INT8 quantization result of the sqlcoder to the huggingface please? This request is very strong, please 🥺
> 
> 已经有了，就在这几天。这个是34B的GPTQ版本，实测加载之后18G显存。此外还有AWQ版本。 TheBloke/sqlcoder-34b-alpha-GPTQ

不知道他用的校准数据集效果咋样
