### ISSUE TITLE
Question about the DDL Schema

### ISSUE THREAD

**Issue by chiragshah285** [defog-ai/sqlcoder#2]
For the DDL statements, ie the create table statements, how important is the descriptions of the columns? Does this help the model figure out the columns to use during inference? Also was RAG tested in liu of fine tuning in terms of performance?

**Comment by rishsriv** [comment]
Thanks for the question! The model works fairly well without column descriptions or table join comments. Though without those, you might get lower accuracy for vague questions.

For example, with the follow DDL statements without any column descriptions – you still get the right answer what questions like "how much customers do we have", or "what is our total revenue". But answers to less complex questions might fail.

```sql
CREATE TABLE products (
  product_id INTEGER PRIMARY KEY,
  name VARCHAR(50),
  price DECIMAL(10,2),
  quantity INTEGER 
);

CREATE TABLE customers (
  customer_id INTEGER PRIMARY KEY,
  name VARCHAR(50),
  address VARCHAR(100)
);

CREATE TABLE salespeople (
  salesperson_id INTEGER PRIMARY KEY,
  name VARCHAR(50),
  region VARCHAR(50)
);

CREATE TABLE sales (
  sale_id INTEGER PRIMARY KEY,
  product_id INTEGER,
  customer_id INTEGER,
  salesperson_id INTEGER,
  sale_date DATE,
  quantity INTEGER
);

CREATE TABLE product_suppliers (
  supplier_id INTEGER PRIMARY KEY,
  product_id INTEGER,
  supply_price DECIMAL(10,2)
);

-- sales.product_id can be joined with products.product_id
-- sales.customer_id can be joined with customers.customer_id 
-- sales.salesperson_id can be joined with salespeople.salesperson_id
-- product_suppliers.product_id can be joined with products.product_id
```
