### ISSUE TITLE
How can I specify the database version I want to generate SQL for?

### ISSUE THREAD

**Issue by peterbjorkmarker** [defog-ai/sqlcoder#28]
I can see on you website that you support different database engines. How can I specify this when using the model directly?

Thanks!

Peter

**Comment by rishsriv** [comment]
Hi there! Unfortunately, the open-source model only supports Postgres right now. We hope to release models for other SQL dialects in the near future.

**Comment by peterbjorkmarker** [comment]
Thanks for the info!
