### ISSUE TITLE
How can I use this model to make it conversational?

### ISSUE THREAD

**Issue by HarjyotKaur** [defog-ai/sqlcoder#30]
@rishsriv @wendy-aw 
Currently I am using the code provided in the google colab notebook to use the model in my local environment. The model is giving incorrect queries when asking questions that should be solved with nested queries. For example:

Table has four columns: Name, School, Standard, Marks
Question: Get the maximum marks for each school and standard, and get count with marks greater than 75% of the maximum for each school and standard; 

Output is:
SELECT school,
       standard,
       MAX(Marks) AS max_marks,
       SUM(CASE
               WHEN Marks> 0.75 * MAX(Marks) THEN 1
               ELSE 0
           END) AS marks_75_percent_max_marks
FROM students
GROUP BY school,
         standard;
         

Now this gives the error of **Nested Aggregation**; how can we tell the model to correct for that?

I tried combining the question 1, response of question 1 and question 2; but the model just give back the question in this case

**Comment by rishsriv** [comment]
This model is not instruction fine tuned yet, and will not work with this conversational style out of the box.

Please use the [suggested prompt in prompt.md](https://github.com/defog-ai/sqlcoder/blob/main/prompt.md) instead.
