### ISSUE TITLE
Difference in execution time between ipynb and py files and optimal setting

### ISSUE THREAD

**Issue by howon-ryu** [defog-ai/sqlcoder#31]
Thank you for making a good model. I'm a junior developer who just got into this field with an interest. I'm currently testing using this model. I am using a6000 48gb gpu and rryzen 3975wx cpu in a docker environment. I have a question regarding the execution time.
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
[inference.py]
model = AutoModelForCausalLM.from_pretrained(
model_name,
trust_remote_code=True,
torch_dtype=torch.bfloat16,
device_map="auto",
use_cache=True,

)

pipe = pipeline(
"text-generation",
model=model,
tokenizer=tokenizer,
max_new_tokens=400,
do_sample=False,
num_beams=1, # do beam search with 5 beams for high quality results
)
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
[defog-sqlcoder-colab.ipynb]

model_name = "defog/sqlcoder2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
model_name,
trust_remote_code=True,
torch_dtype=torch.bfloat16,

device_map="auto",
use_cache=True,
)

generated_ids = model.generate(
**inputs,
num_return_sequences=1,
eos_token_id=eos_token_id,
pad_token_id=eos_token_id,
max_new_tokens=400,
do_sample=False,
num_beams=1
)
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
Although the two options look the same, it takes 150-180 seconds for py files and 15-23 seconds for ipynb files.

I would appreciate it if you could let me know if there are any other factors or optimal settings that make the time difference.

**Comment by rishsriv** [comment]
Hi there, I suspect you have different environments in your Jupyter notebook and Python files. It's possible that your `py` file environment does not have access to CUDA. You can verify this by running `import torch;torch.cuda.is_available()` within Python.

**Comment by howon-ryu** [comment]
Thank you so much for your response!

ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
if __name__ == "__main__":
# # Parse arguments
print("cuda:",torch.cuda.is_available())
parser = argparse.ArgumentParser(description="Run inference on a question")
parser.add_argument("-q","--question", type=str, help="Question to run inference on")
args = parser.parse_args()
question = args.question
print("Loading a model and generating a SQL query for answering your question...")
start = time.time()
print(run_inference(question))
end = time.time()
print("시간",end - start)
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

I added [print("cuda:",torch.cuda.is_available()) ] 

----response------
root@63408936a352:/workspace/sqlcoder# python inference2.py -q "show all products"
cuda: True
Loading a model and generating a SQL query for answering your question...
------------------
I received a 'True' return.

Additionally, when I used the option model.to _bettertransformer(), it was reduced by about 30 seconds, and I wonder if this option is valid!
Thank you again for your reply!

**Comment by howon-ryu** [comment]
Thank you so much for your response!

ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
if __name__ == "__main__":
# # Parse arguments
print("cuda:",torch.cuda.is_available())
parser = argparse.ArgumentParser(description="Run inference on a question")
parser.add_argument("-q","--question", type=str, help="Question to run inference on")
args = parser.parse_args()
question = args.question
print("Loading a model and generating a SQL query for answering your question...")
start = time.time()
print(run_inference(question))
end = time.time()
print("시간",end - start)
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

I added [print("cuda:",torch.cuda.is_available()) ] 

----response------
root@63408936a352:/workspace/sqlcoder# python inference2.py -q "show all products"
cuda: True
Loading a model and generating a SQL query for answering your question...
------------------
I received a 'True' return.

Additionally, when I used the option model.to _bettertransformer(), it was reduced by about 30 seconds, and I wonder if this option is valid!
Thank you again for your reply!

**Comment by howon-ryu** [comment]
I pressed it wrong, so I opened it again ㅠㅠㅠㅠ
Thank you so much for your response!

ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
if __name__ == "__main__":
# # Parse arguments
print("cuda:",torch.cuda.is_available())
parser = argparse.ArgumentParser(description="Run inference on a question")
parser.add_argument("-q","--question", type=str, help="Question to run inference on")
args = parser.parse_args()
question = args.question
print("Loading a model and generating a SQL query for answering your question...")
start = time.time()
print(run_inference(question))
end = time.time()
print("시간",end - start)
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

I added [print("cuda:",torch.cuda.is_available()) ] 

----response------
root@63408936a352:/workspace/sqlcoder# python inference2.py -q "show all products"
cuda: True
Loading a model and generating a SQL query for answering your question...
------------------
I received a 'True' return.

Additionally, when I used the option model.to _bettertransformer(), it was reduced by about 30 seconds, and I wonder if this option is valid!
Thank you again for your reply!

**Comment by rishsriv** [comment]
Hmm, I suspect it's an environment issue – perhaps you can check if `print(torch.version.cuda)` is the same across both the Jupyter notebook and inside your Python script?

And yes, you can absolutely use `model.to_bettertransformer()`

**Comment by howon-ryu** [comment]
Thank you for your response!
[inference.py]
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ


print("cuda:",torch.cuda.is_available())
print(torch.version.cuda)

(response)
root@63408936a352:/workspace/sqlcoder# python inference.py -q "show all products"
cuda: True
11.7
Loading a model and generating a SQL query for answering your question...
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ



[defog-sqlcoder-colab]
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline

torch.cuda.is_available()
True

print(torch.version.cuda)
11.7
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ


It's confirmed as 11.7 version ㅠㅠㅠ

**Comment by rishsriv** [comment]
Huh. I'm unfortunately unsure why this might be happening and am unable to replicate this behavior on my machine – apologies for that. But would imagine that this is due to some combination of environment misconfigurations.

**Comment by howon-ryu** [comment]
Thank you for your answer! Let's check the environmental variables again. Thank you for sharing a good model

**Comment by howon-ryu** [comment]
I don't know the exact reason, but I succeeded in reducing the time.
First of all, 150-180 seconds included the model loading time. ㅠㅠㅠ
Excluding this time, it takes 50 to 80 seconds.
On ipynb, running for the first time after loading the model takes the same 50-80 seconds.
After that, it was confirmed that generating by changing only the question and prompt takes 15 to 23 seconds, and if you configure it the same in py (generate time only), 15 to 23 seconds will come out.


Is there a reason for the time difference between the execution right after the model load and the execution after that? Thank you!

**Comment by ChenTao98** [comment]
The reason may be that the end token is different in sqlcoder ("```") and sqlcoder2("|endoftext|").
You can modify the code in line 34 of inference.py as follows:

origin:
```
eos_token_id = tokenizer.convert_tokens_to_ids(["```"])[0]
```
modified:
```
eos_token_id = tokenizer.eos_token_id
```
