### ISSUE TITLE
 When I use 6* Tesal T4 (15GB) GPU  resources to run sqlcoder2 model and enter a question like  what is the total number of the table, the model query is very slow and takes about 10 minutes. Is it because my gpu resources are not good?Should I use A100(80GB) gpu?)

### ISSUE THREAD

**Issue by bigmancomeon** [defog-ai/sqlcoder#33]

**Comment by rishsriv** [comment]
Hi there, it seems like the model is using the CPU instead of GPU. We've generally seen inference speeds of ~8-10 seconds on 4xTesla T4 GPUs. Would recommend taking a look at your CUDA configurations.

**Comment by bigmancomeon** [comment]
> Hi there, it seems like the model is using the CPU instead of GPU. We've generally seen inference speeds of ~8-10 seconds on 4xTesla T4 GPUs. Would recommend taking a look at your CUDA configurations.

![1697169642749](https://github.com/defog-ai/sqlcoder/assets/129055247/a4a0596e-ab3b-4399-bec2-ed38a10fc3f9)
As shown in the picture, it shows that the each  GPU resources are already in use, and a total of more than 50 GB of memory is spent. Is it still that the GPU resources are not used?Should I use model=model.cuda()  to  let all model  run in the gpu?

**Comment by rishsriv** [comment]
Not quite sure what the issue might be. It could be an issue with how your GPUs are connected, but no idea what else could be causing this.

**Comment by bigmancomeon** [comment]
> Not quite sure what the issue might be. It could be an issue with how your GPUs are connected, but no idea what else could be causing this.

Do you mean that the multi-card capability of the GPU is not used? Generally, if I want to use multiple gpu cards to run the model for inference, what modifications need to be made to the inference.py file?
