### ISSUE TITLE
max length

### ISSUE THREAD

**Issue by jiangix-paper** [defog-ai/sqlcoder#4]
Hello, I want to know the max sequence length which sqlcoder can process. The length of my sql schema is very long.

**Comment by rishsriv** [comment]
Hi there! The context window is 2048 tokens, but you can use a pruning function to restrict it to only the tables/columns that are relevant to your question.

We have an example of this [here](https://github.com/defog-ai/sql-eval/blob/main/utils/pruning.py) – but will document it properly and share more code for inference shortly

**Comment by durgesh-rathod-sf** [comment]
> Hi there! The context window is 2048 tokens, but you can use a pruning function to restrict it to only the tables/columns that are relevant to your question.
> 
> We have an example of this [here](https://github.com/defog-ai/sql-eval/blob/main/utils/pruning.py) – but will document it properly and share more code for inference shortly

How to create embedding.pkl file that is required for the pruning ? Please see [this](https://github.com/defog-ai/sql-eval/issues/22https://github.com/defog-ai/sql-eval/issues/22)

**Comment by Kshitizkhandel** [comment]
> Hi there! The context window is 2048 tokens, but you can use a pruning function to restrict it to only the tables/columns that are relevant to your question.
> 
> We have an example of this [here](https://github.com/defog-ai/sql-eval/blob/main/utils/pruning.py) – but will document it properly and share more code for inference shortly

Is there any documentation pertaining how to use pruning.py? Would be really helpful
