### ISSUE TITLE
Can the sqlcoder2 model be converted into a TensorRT (trt) model for acceleration using TensorRT?

### ISSUE THREAD

**Issue by RiwenY** [defog-ai/sqlcoder#42]
Hi team，

I am currently using an A10G (GPU) for inference, the inference time is basically about 16 seconds, and I hope to reduce the inference time.
I have tried converting the sqlcoder2 model into a .pth model, then converting the .pth model into an ONNX model, and finally I hope to transform it into a trt model to accelerate using TensorRT.
An error occurs while I am converting the sqlcoder2 .pth model into an ONNX model, so I can't perform the subsequent conversion.
I would like to know whether it is possible to convert the sqlcoder2 model to a TensorRT (trt) model for acceleration with TensorRT?

**Comment by bigmancomeon** [comment]
> Hi team，
> 
> I am currently using an A10G (GPU) for inference, the inference time is basically about 16 seconds, and I hope to reduce the inference time. I have tried converting the sqlcoder2 model into a .pth model, then converting the .pth model into an ONNX model, and finally I hope to transform it into a trt model to accelerate using TensorRT. An error occurs while I am converting the sqlcoder2 .pth model into an ONNX model, so I can't perform the subsequent conversion. I would like to know whether it is possible to convert the sqlcoder2 model to a TensorRT (trt) model for acceleration with TensorRT?

Do you use one single  A10G GPU with 24g gpu memory?Your model runs in 16 seconds, this is faster than mine. did you make any changes to the parameters of the infenerce.py  file  when using the sqlcoder2 model

**Comment by RiwenY** [comment]
Yes. I adjusted the parameters.
The parameters are as follows: 

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    trust_remote_code=True,
    torch_dtype=torch.float32,
    load_in_4bit=True,
    device_map="auto",
    use_cache=True,
)


pipe = pipeline(
    "text-generation", 
    model=model,
    tokenizer=tokenizer, 
    max_new_tokens=300,
    do_sample=False, 
    num_beams=1,
)

**Comment by RiwenY** [comment]
> > Hi team，
> > I am currently using an A10G (GPU) for inference, the inference time is basically about 16 seconds, and I hope to reduce the inference time. I have tried converting the sqlcoder2 model into a .pth model, then converting the .pth model into an ONNX model, and finally I hope to transform it into a trt model to accelerate using TensorRT. An error occurs while I am converting the sqlcoder2 .pth model into an ONNX model, so I can't perform the subsequent conversion. I would like to know whether it is possible to convert the sqlcoder2 model to a TensorRT (trt) model for acceleration with TensorRT?
> 
> Do you use one single A10G GPU with 24g gpu memory?Your model runs in 16 seconds, this is faster than mine. did you make any changes to the parameters of the infenerce.py file when using the sqlcoder2 model

Yes. I adjusted the parameters.
The parameters are as follows: 
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    trust_remote_code=True,
    torch_dtype=torch.float32,
    load_in_4bit=True,
    device_map="auto",
    use_cache=True,
)


pipe = pipeline(
    "text-generation", 
    model=model,
    tokenizer=tokenizer, 
    max_new_tokens=300,
    do_sample=False, 
    num_beams=1,
)

**Comment by bigmancomeon** [comment]
> torch_dtype=torch.float32,
> load_in_4bit=True,

Why  you change  this  two items,I only use torch_dtype=torch.float16, which is faster than yours

**Comment by RiwenY** [comment]
> > torch_dtype=torch.float32,
> > load_in_4bit=True,
> 
> Why you change this two items,I only use torch_dtype=torch.float16, which is faster than yours

Because I use torch_dtype=torch.float16, the inference time reaches 100 seconds, which is too long. After adjusting parameters, I can shorten the inference time.
Today, I pulled the code from GitHub and changed eos_token_id = tokenizer.eos_token_id, the current inference time can be shortened to 6.4 seconds.

**Comment by bigmancomeon** [comment]
> > > torch_dtype=torch.float32,
> > > load_in_4bit=True,
> > 
> > 
> > Why you change this two items,I only use torch_dtype=torch.float16, which is faster than yours
> 
> Because I use torch_dtype=torch.float16, the inference time reaches 100 seconds, which is too long. After adjusting parameters, I can shorten the inference time. Today, I pulled the code from GitHub and changed eos_token_id = tokenizer.eos_token_id, the current inference time can be shortened to 6.4 seconds.

What is your input data? Can you share it with me?

**Comment by RiwenY** [comment]
> > > > torch_dtype=torch.float32,
> > > > load_in_4bit=True,
> > > 
> > > 
> > > Why you change this two items,I only use torch_dtype=torch.float16, which is faster than yours
> > 
> > 
> > Because I use torch_dtype=torch.float16, the inference time reaches 100 seconds, which is too long. After adjusting parameters, I can shorten the inference time. Today, I pulled the code from GitHub and changed eos_token_id = tokenizer.eos_token_id, the current inference time can be shortened to 6.4 seconds.
> 
> What is your input data? Can you share it with me?

Using the test statement of SQLCoder model, "Do we get more revenue from customers in New York compared to customers in San Francisco? Give me the total revenue for each city, and the difference between the two." . I set num_beams=1, the inference time is shorter, but the quality of the inferred SQL is also diminished.

**Comment by bigmancomeon** [comment]
> > > > > torch_dtype=torch.float32,
> > > > > load_in_4bit=True,
> > > > 
> > > > 
> > > > Why you change this two items,I only use torch_dtype=torch.float16, which is faster than yours
> > > 
> > > 
> > > Because I use torch_dtype=torch.float16, the inference time reaches 100 seconds, which is too long. After adjusting parameters, I can shorten the inference time. Today, I pulled the code from GitHub and changed eos_token_id = tokenizer.eos_token_id, the current inference time can be shortened to 6.4 seconds.
> > 
> > 
> > What is your input data? Can you share it with me?
> 
> Using the test statement of SQLCoder model, "Do we get more revenue from customers in New York compared to customers in San Francisco? Give me the total revenue for each city, and the difference between the two." . I set num_beams=1, the inference time is shorter, but the quality of the inferred SQL is also diminished.

![1698054156039](https://github.com/defog-ai/sqlcoder/assets/129055247/08923288-c151-498f-a96c-bf5c7861e3e4)

I used one single T4(16 GB) GPU,
set torch_dtype=torch.float32,load_in_4bit=True,num_beams=1  to run the sqlcoder2 model and use
"Do we get more revenue from customers in New York compared to customers in San Francisco? Give me the total revenue for each city, and the difference between the two."
 as input. It took 56 seconds. The result is as shown in the picture. 
I don’t think it is right. What is your output? Have you ever encountered this kind of output?

**Comment by RiwenY** [comment]
> > > > > > torch_dtype=torch.float32,
> > > > > > load_in_4bit=True,
> > > > > 
> > > > > 
> > > > > Why you change this two items,I only use torch_dtype=torch.float16, which is faster than yours
> > > > 
> > > > 
> > > > Because I use torch_dtype=torch.float16, the inference time reaches 100 seconds, which is too long. After adjusting parameters, I can shorten the inference time. Today, I pulled the code from GitHub and changed eos_token_id = tokenizer.eos_token_id, the current inference time can be shortened to 6.4 seconds.
> > > 
> > > 
> > > What is your input data? Can you share it with me?
> > 
> > 
> > Using the test statement of SQLCoder model, "Do we get more revenue from customers in New York compared to customers in San Francisco? Give me the total revenue for each city, and the difference between the two." . I set num_beams=1, the inference time is shorter, but the quality of the inferred SQL is also diminished.
> 
> ![1698054156039](https://user-images.githubusercontent.com/129055247/277295007-08923288-c151-498f-a96c-bf5c7861e3e4.jpg)
> 
> I used one single T4(16 GB) GPU, set torch_dtype=torch.float32,load_in_4bit=True,num_beams=1 to run the sqlcoder2 model and use "Do we get more revenue from customers in New York compared to customers in San Francisco? Give me the total revenue for each city, and the difference between the two." as input. It took 56 seconds. The result is as shown in the picture. I don’t think it is right. What is your output? Have you ever encountered this kind of output?

When I set num_beams=1, the generated SQL is as follows:
SELECT
	customers.address,
	SUM(sales.quantity * sales.price) AS total_revenue,
	(
	SELECT
		SUM(sales.quantity * sales.price)
	FROM
		sales
	WHERE
		customers.address ilike '%New%York%') - (
	SELECT
		SUM(sales.quantity * sales.price)
	FROM
		sales
	WHERE
		customers.address ilike '%San%Francisco%') AS difference
FROM
	sales
JOIN customers ON
	sales.customer_id = customers.customer_id
GROUP BY
	customers.address
ORDER BY
	total_revenue DESC NULLS LAST;

When I set num_beams=5, the inference time reached 100 seconds, and the generated SQL is as follows:
WITH ny_sales AS (
SELECT
	SUM(sales.quantity * sales.price) AS total_revenue_ny
FROM
	sales
JOIN customers ON
	sales.customer_id = customers.customer_id
WHERE
	customers.address ilike '%New York%'),
sf_sales AS (
SELECT
	SUM(sales.quantity * sales.price) AS total_revenue_sf
FROM
	sales
JOIN customers ON
	sales.customer_id = customers.customer_id
WHERE
	customers.address ilike '%San Francisco%')
SELECT
	total_revenue_ny,
	total_revenue_sf,
	total_revenue_ny - total_revenue_sf AS revenue_difference
FROM
	ny_sales,
	sf_sales;

**Comment by RiwenY** [comment]
> > torch_dtype=torch.float32,load_in_4bit=True,num_beams=1
> 
> When you use the sqlcoder2 model, besides setting torch_dtype=torch.float32,load_in_4bit=True,num_beams=1 in the inference.py file, do you also set any other parameters? Because I only changed these three parameters and run the sqlcoder2 model, but the results were different from yours, and My results were poor.
> 
> > > > > > > > torch_dtype=torch.float32,
> > > > > > > > load_in_4bit=True,
> > > > > > > 
> > > > > > > 
> > > > > > > Why you change this two items,I only use torch_dtype=torch.float16, which is faster than yours
> > > > > > 
> > > > > > 
> > > > > > Because I use torch_dtype=torch.float16, the inference time reaches 100 seconds, which is too long. After adjusting parameters, I can shorten the inference time. Today, I pulled the code from GitHub and changed eos_token_id = tokenizer.eos_token_id, the current inference time can be shortened to 6.4 seconds.
> > > > > 
> > > > > 
> > > > > What is your input data? Can you share it with me?
> > > > 
> > > > 
> > > > Using the test statement of SQLCoder model, "Do we get more revenue from customers in New York compared to customers in San Francisco? Give me the total revenue for each city, and the difference between the two." . I set num_beams=1, the inference time is shorter, but the quality of the inferred SQL is also diminished.
> > > 
> > > 
> > > ![1698054156039](https://user-images.githubusercontent.com/129055247/277295007-08923288-c151-498f-a96c-bf5c7861e3e4.jpg)
> > > I used one single T4(16 GB) GPU, set torch_dtype=torch.float32,load_in_4bit=True,num_beams=1 to run the sqlcoder2 model and use "Do we get more revenue from customers in New York compared to customers in San Francisco? Give me the total revenue for each city, and the difference between the two." as input. It took 56 seconds. The result is as shown in the picture. I don’t think it is right. What is your output? Have you ever encountered this kind of output?
> > 
> > 
> > When I set num_beams=1, the generated SQL is as follows: SELECT customers.address, SUM(sales.quantity * sales.price) AS total_revenue, ( SELECT SUM(sales.quantity * sales.price) FROM sales WHERE customers.address ilike '%New%York%') - ( SELECT SUM(sales.quantity * sales.price) FROM sales WHERE customers.address ilike '%San%Francisco%') AS difference FROM sales JOIN customers ON sales.customer_id = customers.customer_id GROUP BY customers.address ORDER BY total_revenue DESC NULLS LAST;
> > When I set num_beams=5, the inference time reached 100 seconds, and the generated SQL is as follows: WITH ny_sales AS ( SELECT SUM(sales.quantity * sales.price) AS total_revenue_ny FROM sales JOIN customers ON sales.customer_id = customers.customer_id WHERE customers.address ilike '%New York%'), sf_sales AS ( SELECT SUM(sales.quantity * sales.price) AS total_revenue_sf FROM sales JOIN customers ON sales.customer_id = customers.customer_id WHERE customers.address ilike '%San Francisco%') SELECT total_revenue_ny, total_revenue_sf, total_revenue_ny - total_revenue_sf AS revenue_difference FROM ny_sales, sf_sales;
> 
> When you use the sqlcoder2 model, besides setting torch_dtype=torch.float32,load_in_4bit=True,num_beams=1 in the inference.py file, do you also set any other parameters? Because I only changed these three parameters and run the sqlcoder2 model, but the results were different from yours, and My results were poor.

I only configured these three parameters, without any other modifications.

**Comment by Kshitizkhandel** [comment]
> Hi team，
> 
> I am currently using an A10G (GPU) for inference, the inference time is basically about 16 seconds, and I hope to reduce the inference time. I have tried converting the sqlcoder2 model into a .pth model, then converting the .pth model into an ONNX model, and finally I hope to transform it into a trt model to accelerate using TensorRT. An error occurs while I am converting the sqlcoder2 .pth model into an ONNX model, so I can't perform the subsequent conversion. I would like to know whether it is possible to convert the sqlcoder2 model to a TensorRT (trt) model for acceleration with TensorRT?

Were you able to convert sqlcoder model into tensorrt format? Do you happen to know if we can do the same for sqlcoder70B alpha?

**Comment by ramaneswaran** [comment]
Hi, have you tested out TensorRT-LLM. It is an extension of TensorRT, specifically for LLMs. Since sqlcoder is based on Llama2, follow the example given here: https://github.com/NVIDIA/TensorRT-LLM/
