### ISSUE TITLE
Does this model support Chinese? If support , how is the inference ability?

### ISSUE THREAD

**Issue by bigmancomeon** [defog-ai/sqlcoder#43]

**Comment by nuaabuaa07** [comment]
I use the following metadata and it works well!

CREATE TABLE xxx.xxx_1d
(
fre_province STRING COMMNENT '常驻省份'
,fre_city_level STRING COMMNENT '常驻城市等级。eg：五线城市 | 四线城市 | 三线城市 | 二线城市 | 一线城市 | 新一线城市'
,age_segment STRING COMMNENT '年龄分段。eg："50+" - 50多岁 | "31-40" - 31到40岁,30多岁 | "40-49" - 40多岁 | "24-30" - 中年,24多岁 | "18-23" - 青年,18多岁 | "12-17" - 12多岁,少年 | "0-12" - 儿童,小学生,孩子,12岁以下'
,play_live_cnt BIGINT COMMENT '直播观看次数'
,play_live_duration BIGINT COMMENT '直播观看时长'
,total_cost_amt BIGINT COMMENT '直播付费金额'
,send_gift_amt BIGINT COMMENT '直播送礼金额'
,play_live_user_num BIGINT COMMENT '直播观看用户数'
,total_cost_user_num BIGINT COMMENT '直播付费用户数'
,send_gift_user_num BIGINT COMMENT '直播送礼用户数'
,play_cost_user_num BIGINT COMMENT '直播观看且付费用户数'
,active_user_num BIGINT COMMENT '活跃用户数'
,dimensions_code STRING COMMENT '维度代码-为移动端冗余'
,not_spam_play_live_cnt BIGINT COMMENT '直播观看次数-非反作弊'
,not_spam_play_live_duration BIGINT COMMENT '直播观看时长-非反作弊'
,spam_play_live_user_num BIGINT COMMENT '直播观看用户数-反作弊'
,active_cost_user_num BIGINT COMMENT '主动付费用户数'
,only_passive_cost_user_num BIGINT COMMENT '仅被动付费用户数'
)
PARTITIONED BY (
p_date STRING COMMENT '日期分区，格式为yyyyMMdd，eg:20200101'
)

question: 查看不同省份的活跃用户数

**Comment by bigmancomeon** [comment]
> I use the following metadata and it works well!
> 
> CREATE TABLE xxx.xxx_1d ( fre_province STRING COMMNENT '常驻省份' ,fre_city_level STRING COMMNENT '常驻城市等级。eg：五线城市 | 四线城市 | 三线城市 | 二线城市 | 一线城市 | 新一线城市' ,age_segment STRING COMMNENT '年龄分段。eg："50+" - 50多岁 | "31-40" - 31到40岁,30多岁 | "40-49" - 40多岁 | "24-30" - 中年,24多岁 | "18-23" - 青年,18多岁 | "12-17" - 12多岁,少年 | "0-12" - 儿童,小学生,孩子,12岁以下' ,play_live_cnt BIGINT COMMENT '直播观看次数' ,play_live_duration BIGINT COMMENT '直播观看时长' ,total_cost_amt BIGINT COMMENT '直播付费金额' ,send_gift_amt BIGINT COMMENT '直播送礼金额' ,play_live_user_num BIGINT COMMENT '直播观看用户数' ,total_cost_user_num BIGINT COMMENT '直播付费用户数' ,send_gift_user_num BIGINT COMMENT '直播送礼用户数' ,play_cost_user_num BIGINT COMMENT '直播观看且付费用户数' ,active_user_num BIGINT COMMENT '活跃用户数' ,dimensions_code STRING COMMENT '维度代码-为移动端冗余' ,not_spam_play_live_cnt BIGINT COMMENT '直播观看次数-非反作弊' ,not_spam_play_live_duration BIGINT COMMENT '直播观看时长-非反作弊' ,spam_play_live_user_num BIGINT COMMENT '直播观看用户数-反作弊' ,active_cost_user_num BIGINT COMMENT '主动付费用户数' ,only_passive_cost_user_num BIGINT COMMENT '仅被动付费用户数' ) PARTITIONED BY ( p_date STRING COMMENT '日期分区，格式为yyyyMMdd，eg:20200101' )
> 
> question: 查看不同省份的活跃用户数

I just tried it and it works.In addition,have you tried the effect of multiple field query, such as querying 20 or 30 fields in a table with 60 fields according to query conditions?
