### ISSUE TITLE
How to fine tune on specific schema?

### ISSUE THREAD

**Issue by buddyroo30** [defog-ai/sqlcoder#45]
In your blog post where you open-sourced sqlcoder, you note that "When fine-tuned on an individual database schema, it matches or outperforms GPT-4 performance." But how exactly do you do this, i.e. fine tune the model to a specific schema? Do you have any documentation how to do this? Do we simply need to generate many many examples for our specific schema (i.e. English language text and corresponding SQL for it) and use that for fine tuning? What specifically should the training data look like? Thanks.

**Comment by Dev-Force** [comment]
Bump, If anyone has successfully done this before, please give some tips.
