### ISSUE TITLE
Pruning function meta data

### ISSUE THREAD

**Issue by lalehsg** [defog-ai/sqlcoder#53]
Hi all. 

I have been working with the pruning function for my use case and it seems to be effective. I was wondering if you have a suggestion for automating the NER labelling of the column names. The manual tagging is a pretty tedious and inefficient task. 

Thanks,
Laleh

**Comment by rishsriv** [comment]
Hi there, thanks for the issue. We’re working on this and should be able to open-source an automated NER labeler in early Jan!

**Comment by lalehsg** [comment]
This is fantastic! Looking forward to it.

**Comment by yashkhurana24** [comment]
Hey, is there an update to this?
