### ISSUE TITLE
No results when running sqlcoder34B-alpha

### ISSUE THREAD

**Issue by SiChengliang** [defog-ai/sqlcoder#54]
Hi team and other friends,

There are no results when running sqlcoder34B-alpha model with sample code and database. I have checked pipe result, there is no relsult with beam_search = 5 setting. And if I set beam_search = 1, the performance is very poor and I believe it's not the model's performance.
![image](https://github.com/defog-ai/sqlcoder/assets/19571712/7f4d65ca-d8fe-43d8-8a24-180369aed0aa)

Moreover, sqlcoder2 do have relsults, but should modify sample code as below.
![image](https://github.com/defog-ai/sqlcoder/assets/19571712/ae7c9e06-e758-4421-8e3f-a7b85fb9365d)

Developed on 2*A100 40GB with no quantification
Any ideas with this issue, thanks a lot.

**Comment by SiChengliang** [comment]
I figure out why there are no relsult. for me, it's because the library version is too low, should update. finally, update the environment to 
![image](https://github.com/defog-ai/sqlcoder/assets/19571712/7c6a06a7-0124-42d2-ad77-f54541fe5b64)
it has output.

**Comment by wongjingping** [comment]
Hi could you share the prompt that you used? The generated text contains the prompt so one would need to replace the final characters accordingly.

**Comment by ighoshsubho** [comment]
I would like to work on this issue. Can you assign it to me?

**Comment by rishsriv** [comment]
Hi there, this was fixed in #63. Closing for now – please feel free to reopen if you still run into issues.
