### ISSUE TITLE
Can sqlcoder generate Mysql query？

### ISSUE THREAD

**Issue by Peroplex** [defog-ai/sqlcoder#57]
The model can generate postgre query with ILIKE and NULLS LAST, and Mysql can't use them. How to solve the problem?

**Comment by yanxuexu007** [comment]
Same question. Does Any prompt format support to return the sql query format which I need？

**Comment by davezflo** [comment]
Agreed - I'd like to use this with Sqlite (simple DB). Is there any way to prompt this to not use postgres-only syntax??

**Comment by buddyroo30** [comment]
You could potentially use this to convert a generated PostgreSQL query to your desired format (like MySQL): https://github.com/tobymao/sqlglot

**Comment by davezflo** [comment]
> You could potentially use this to convert a generated PostgreSQL query to your desired format (like MySQL): https://github.com/tobymao/sqlglot

Thanks @buddyroo30  - I may give that a shot. I've just been playing around with this LLM and Phi-2 to generate queries from English and then visualizations from the results. (https://github.com/davezflo/dbviz). I ended up going with postgreSQL, but I still have a sqlite3 version. This tool might help me, no?
