### ISSUE TITLE
Bug in inference.py

### ISSUE THREAD

**Issue by buddyroo30** [defog-ai/sqlcoder#59]
There seems to be a simple bug in inference.py, as I just test ran sqlcoder and it didn't work until I made a small fix. Basically it is in this piece of code:

generated_query = (
        pipe(
            prompt,
            num_return_sequences=1,
            eos_token_id=eos_token_id,
            pad_token_id=eos_token_id,
        )[0]["generated_text"]
        .split("```sql")[-1]
        .split("```")[0]
        .split(";")[0]
        .strip()
        + ";"
    )

you need to change .split("\`\`\`sql")[-1] --> .split("SQL\n\`\`\`") --- doing this is what fixed it for me.

**Comment by buddyroo30** [comment]
So I tried the fix, but it is broken again because the format of the prompt.md file was changed. I made another fix, would be happy to share via pull request.

**Comment by rishsriv** [comment]
Ah apologies for that! A PR would be great, if not will make a fix in a few hours!

**Comment by rishsriv** [comment]
Fixed, thanks for reporting!
