### ISSUE TITLE
Special Instruction while inferencing locally deployed model

### ISSUE THREAD

**Issue by prayagkb** [defog-ai/sqlcoder#61]
Deployed SQLCoder-34B Locally, But couldn't provide special instructions as shown in [Demo](https://defog.ai/sqlcoder-demo/). Where & How can I write special instructions ?

**Comment by Kirushikesh** [comment]
If i am not wrong the special instructions appears in the Instructions section, This [notebook](https://github.com/defog-ai/sqlcoder/blob/main/defog-sqlcoder-colab.ipynb) in the repo contains the inference of the model with the schema and question, where **Adhere to these rules:** is what ig to be the special instructions section.

**Comment by rishsriv** [comment]
Hi there! You can add instructions anywhere in the prompt you construct – either in the instructions section as @Kirushikesh mentioned, or elsewhere in the prompt. The exact location will vary depending on your specific use-case.

**Comment by Kirushikesh** [comment]
Also @rishsriv, thanks for the reply. What is the actual prompt format used for finetuning the codellama model, mostly i found the Task/Database Schema/Answer, but in the notebook i found a new format of Instructions/Input/Response.

**Comment by rishsriv** [comment]
It's a mixture of formats – you should pretty good results with the file in `prompt.md`
