### ISSUE TITLE
Fine-tune Custom Dataset Using defog/sqlcoder-70b-alpha

### ISSUE THREAD

**Issue by sanipanwala** [defog-ai/sqlcoder#64]
Hello,

Can we fine-tune the **defog/sqlcoder-70b-alpha** model with our custom dataset? If yes then what is the format of data?

Thanks.

**Comment by rishsriv** [comment]
No particular format -- use whatever works best for you!

**Comment by kmhari** [comment]
Could you share a couple sample from your dataset for us to understand better?
