### ISSUE TITLE
Reasoning with the sql output

### ISSUE THREAD

**Issue by addyag93** [defog-ai/sqlcoder#66]
Hi, 
I have been trying sqlcoder 34b model on my large database using pruning, but model cannot handle out of domain queries well as expected. It always generate sql no matter whether that column is present in the schema or not. I have two questions:
- how to make model to handle out of domain queries via prompting instructions. as it tried appending in prompt.md but its not that accurate.
-  If I can get the reasoning as to how  generated a SQL query, that would also help to mitigate some of out of domain queries. How can we do it via prompting?

Can you please help with above?

Thanks
Aditya

**Comment by rishsriv** [comment]
Hi Aditya, could you give us a couple of examples of the full prompt that you're using? That'll help us understand the problem you're facing better.

Also, could you clarify what you mean by out of domain queries? Thanks!

**Comment by addyag93** [comment]
Hi , 

I am using the same prompt as provided in the repo, just added instructions section after :
```
"""## Task
                    Generate a SQL query to answer the following question:""" + "\n"+\
                    user_query["query"] + \
                    """\n\n### Instructions
                    - If not sure with the query response, return I don't know."""+\
                    """\n\n ### Database Schema
                    This query will run on a database whose schema is represented in this string:\n"""+\
                    schema +"\n\n"+\
                    """### SQL
                      Given the database schema, here is the SQL query that answers """+user_query["query"] +"\n\n"+\
                    """```sql"""
```
**I will rather call it in-domain out of domain queries like:**
- Which schools have science labs? : though there is no column in my table for science labs, it assumed a column e.g science stream present or not and provided the answer. it should either give reasoning or reply with it don't know.
- how many schools are there in say jamnagar? : it miss such queries as well as it don't understand what jamnagar it so map it to state column or sometimes district columns, even after  adding "jamnagar" as part of column district_name.

Any help would be very useful.

Thanks
Aditya

**Comment by rishsriv** [comment]
Thanks! Could you please share your schema as well please? That will help us understand this better and recommend a better prompt

**Comment by addyag93** [comment]
Yes. 
following is indomain-out of domain query
`query : Are there any mobile schools in district Jamnagar for nomadic communities?`
`schema: CREATE TABLE sch_master (district_name text, --Name of the district where the school is located 
  sch_loc_rural_urban text, --Type of school location (RURAL, URBAN, Possible Mistake)
  pincode bigint, --Postal code of the school location
  village_ward_name text, --Name of the village or village ward
  school_name text, --Name of the school for the udise code
  block_name text, --Name of the block where the school is located
  longitude bigint, --Longitude coordinate of the school location, sch_code VARCHAR(25) -- Primary Key, Unique code for every school in database); 
 CREATE TABLE sch_profile (resi_sch_type text, --Type of residential school [Not Defined, Ashram (Govt.), Model School, Non-Ashram (Govt.), Jawahar Navodaya Vidyalaya, Other-Boarding, Private-Boarding, KGBV, Eklavya Model Residential School, Netaji Subhash Residential School)
  mthr_tongue_pri text, --Mother tongue of primary students
  distance_upr_to_govt_sch bigint, --Distance from upper primary school to government school
  distance_pri_to_govt_sch bigint, --Distance from primary school to government school
  spltrg_py_enrol_girls bigint, --Special training program enrollment for girls
  distance_sec_to_govt_sch bigint, --Distance from secondary school to government school
  num_upr_sch_in_cmplx bigint, --Number of upper primary schools in complex
  distance_hsec_to_govt_sch bigint, --Distance from higher secondary school to government school
  num_pri_sch_in_cmplx bigint, --Number of primary schools in complex
  spltrg_py_enrol_boys bigint, --Special training program enrollment for boys
  resi_sch_yn text, --Residential school type (Non-Residential, Completely Residential, Partially Residential)
  num_hsec_sch_in_cmplx bigint, --Number of higher secondary schools in complex
  num_sec_sch_in_cmplx bigint, --Number of secondary schools in complex
  sch_hrs_stu_upr bigint, --School hours per student in upper primary school
  sch_hrs_stu_hsec bigint, --School hours per student in higher secondary school
  sch_hrs_teacher_upr bigint, --School hours per teacher in upper primary school, sch_code VARCHAR(25) -- Primary Key, Unique code for every school in database); 
 CREATE TABLE sch_facility (
  bld_blk bigint, --Number of school buildings/blocks
  sch_code text, --school code
  clsrms_upr bigint, --Number of upper primary classrooms
  clsrms_pri bigint, --Number of primary classrooms
  clsrms_hsec bigint, --Number of higher secondary classrooms
  cls_rm_for_instrc bigint, --Number of classrooms used for instruction
  clsrms_pre_pri bigint, --Number of pre-primary classrooms
  num_cls_rms_gd_cond_pucca bigint, --Number of pucca classrooms in good condition
  cls_rm_need_min_repr_pucca bigint, --Number of pucca classrooms needing minor repairs
  ict_instr_type text, --Type of instruction for ICT (9, Full Time, Not Available, Part Time)
  cls_rm_under_cstrc bigint, --Number of classrooms under construction
  clsrms_sec bigint, --Number of secondary classrooms
  cls_rm_need_maj_repr bigint, --Number of classrooms needing major repairs
  mobile_fun bigint, --Number of functional mobile devices, sch_code VARCHAR(25) -- Primary Key, Unique code for every school in database);
-- sch_master.sch_code can be joined with sch_profile.sch_code 
 -- sch_master.sch_code can be joined with sch_facility.sch_code 
 -- sch_profile.sch_code can be joined with sch_facility.sch_code`
 
`SELECT COUNT(*) FROM sch_master JOIN sch_profile ON sch_master.sch_code = sch_code.udise_sch_code JOIN sch_facility ON sch_code.udise_sch_code = sch_facility.sch_code WHERE sch_master.district_name ilike '%JAMNAGAR%' AND sch_profile.resi_sch_type ilike '%Mobile%' AND sch_facility.mobile_fun > 0;`

in sql query : resi_sch_type has no value mobile and mobile_fun is no. of phone functions, not mobile schools. 
thanks 
aditya

**Comment by rishsriv** [comment]
I see – you should use the `defog/sqlcoder-7b-2` model for this. The 34B model will soon get these capabilities, but they have not been ported over just yet.

The [new 7b model](https://huggingface.co/defog/sqlcoder-7b-2) seems to handle this like you would expect! The image below is from our gradio app, which you can run [here](https://github.com/defog-ai/sqlcoder-gradio/)

<img width="1353" alt="image" src="https://github.com/defog-ai/sqlcoder/assets/5008293/29a3c03f-b457-41ab-a84e-d2d09eed5897">

Closing this for now, but please feel free to reopen if you still have issues!

**Comment by addyag93** [comment]
Hi, 

I have tested sqlcoder 7b-2 model on this query. Sometimes it gives the answer as above, sometime its hallucinates. I have also tried few in-domain queries with this new model which were working fine with 34b model. For those queries, it sometimes give  SELECT 'I do not know' AS answer; 
Prompt I am using from [here](https://github.com/defog-ai/sqlcoder/blob/main/prompt.md)
Inference parameters:
        ```
"do_sample": False,
        "max_new_tokens": 300,
        "temperature": 0.1,
        "repetition_penalty": 1.1,
        "return_full_text":False,
        "num_beams":4,
```
Can you please help on how to prevent this model from hallucinating. 

Thanks
Aditya

**Comment by rishsriv** [comment]
Ah keep your temperature to 0 and repetition_penalty to 1.1. With temperature 0.1, you will always get some randomness in the results.

Would recommend using the `run_inference` function [here](https://github.com/defog-ai/sqlcoder/blob/983d446d12e8d368a6fefba8945b6652eb98b634/inference.py#L29) for best results.

**Comment by addyag93** [comment]
So i have removed temperature from my sagemaker inference endpoint as it ask for it be positive, not 0. 

I can try running using the run_inference function that you have shared instead of SageMaker endpoint, any specific observation from you on using transformer based inference rather then SageMaker inference. 

Also my metadata.sql with column descriptions,  is more than accepted input limit of 2048 tokens, so I am using pruning. Do you think by pruning as I am not giving the model more context of other columns to compare, it might be given random responses?

Thanks
Aditya

**Comment by rishsriv** [comment]
Try setting temperature to a tiny number (like 0.0001) – it will have roughly the same effect and remove randomness.

The Codellama context limit is 100k, so not sure if the input limit is a Sagemaker specific thing. But with temperature=0 (or a number close enough to 0), you will always get deterministic responses that you can then fix with better prompting!

**Comment by addyag93** [comment]
@rishsriv By input limit I mean input token length which is 2048 tokens for sqlcoder,  so i need to apply pruning for large tables that go beyond token limit of 2048. 

Regarding prompting you mean adding more instructions, right? Also is there a way to get explanations as how the sql generated, because this way i can enhance the instructions?

Thanks
Aditya
