### ISSUE TITLE
Launch Error

### ISSUE THREAD

**Issue by oguzhantortop** [defog-ai/sqlcoder#68]
Hello, I am getting following error when I try to launch sqlcoder launch on osx using apple silicon. Tried to update python, tried to install hugging_hub but none of them worked.

Downloading the SQLCoder-7b-2 GGUF file. This is a ~5GB file and may take a long time to download. But once it's downloaded, it will be saved on your machine and you won't have to download it again.
Traceback (most recent call last):
  File "/Users/oguzhan/.pyenv/versions/3.11.7/bin/sqlcoder", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/oguzhan/.pyenv/versions/3.11.7/lib/python3.11/site-packages/sqlcoder/cli.py", line 23, in main
    launch()
  File "/Users/oguzhan/.pyenv/versions/3.11.7/lib/python3.11/site-packages/sqlcoder/cli.py", line 70, in launch
    sqlcoder.hf_hub_download(repo_id="defog/sqlcoder-7b-2", filename="sqlcoder-7b-q5_k_m.gguf", local_dir=defog_path)
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'sqlcoder' has no attribute 'hf_hub_download'

**Comment by rishsriv** [comment]
Apologies! This was because of a typo in the Python library. I have just pushed a fix with `sqlcoder==0.2.3`. Could you please give this another shot?

```
pip uninstall sqlcoder
pip install sqlcoder==0.2.3
```

**Comment by oguzhantortop** [comment]
Thank you, it worked.
