### ISSUE TITLE
How to finetune with defog/sqlcoder model？

### ISSUE THREAD

**Issue by gumanchang** [defog-ai/sqlcoder#7]
Thank you very much for the open source work and models. Now I have a question, I want to fine-tune my SQL dataset, but the language is Chinese, I don't know whether it is supported, and can the fine-tuning script also be open source?

**Comment by rishsriv** [comment]
Hi there, you can use the StarCoder finetuning script and instructions [here](https://github.com/bigcode-project/starcoder#fine-tuning) for fine-tuning the dataset. Just replace the model with `defog/sqlcoder`

**Comment by oliverbj** [comment]
Hey

Sorry for reopening this issue, and perhaps for a noob question. However, are there any examples on how the training data needs to look like?

**Comment by LZZJ** [comment]
> Hey
> 
> Sorry for reopening this issue, and perhaps for a noob question. However, are there any examples on how the training data needs to look like?

I also have the same problem, can you share how to solve it?

**Comment by aitoehigie** [comment]
@oliverbj Did you eventually get your answer?

**Comment by oliverbj** [comment]
Unfortunately not :(

**Comment by gt732** [comment]
@oliverbj did you ever figure it out? I want to try fine tuning sqlcoder
