### ISSUE TITLE
ModuleNotFoundError: No module named 'llama_cpp'

### ISSUE THREAD

**Issue by szymonk92** [defog-ai/sqlcoder#71]
Running **sqlcoder launch** I am getting: `ModuleNotFoundError: No module named 'llama_cpp'`

Python 3.10.13
Env: Conda

__EDIT__
Intel i7
Windows
only integrated GPU

**Comment by rishsriv** [comment]
Hi there, have you followed the setup instructions for Apple Silicon?

`CMAKE_ARGS="-DLLAMA_METAL=on" pip install "sqlcoder[llama-cpp]"`

**Comment by szymonk92** [comment]
I am using Intel i7 with Windows
