### ISSUE TITLE
How can I fine tune sqlcoder-7b 2 model over my onw query?

### ISSUE THREAD

**Issue by kasldsaknf** [defog-ai/sqlcoder#74]

**Comment by rishsriv** [comment]
Hi there, you can use any of the fine-tuning approaches made available by open-source libraries. For instance, using [TRL](https://github.com/huggingface/trl) or [axolotl](https://github.com/OpenAccess-AI-Collective/axolotl)

Please remember to open-source any fine-tunes you make, to comply with the model's `cc-by-sa-4.0` license

**Comment by kasldsaknf** [comment]
Thank you very much for the open source work and models. I dont know it well. Should I use the Llama finetuning script and instructions for defog/sqlcoder-7b-2? I see "llama" tag on the huggingface :)

**Comment by rishsriv** [comment]
Yup - the Llama finetuning script should work well!

**Comment by mellahysf** [comment]
@kasldsaknf  did you have a chance to establish a new finetuning on top of sqlcoder model using your own dataset? if yes please share your script/code.

Thank you.

**Comment by kasldsaknf** [comment]
@mellahysf I haven't fine tune sqlcoder over my own dataset. I think Llama's fine tune code should work. Did you meet some probelms now?

**Comment by kasldsaknf** [comment]
> Yup - the Llama finetuning script should work well!

Thank you. I will try.
