### ISSUE TITLE
The model consistently generates similar responses for different questions with minor variations.

### ISSUE THREAD

**Issue by kchondror** [defog-ai/sqlcoder#77]
I'm using a database schema to store contact and invoice information. The schema includes tables for contacts and invoices, where contacts are associated with companies, and invoices are issued between individuals represented by these contacts.

When querying the model with different questions related to financial data, such as expenses or revenue for specific companies (e.g., "What were the expenses of Microsoft for the year 2023?" or "What was the revenue of Microsoft for the year 2023?"), it consistently provides the same responses.

The db schema:
CREATE TABLE contacts (
  id bigint(20) unsigned NOT NULL AUTO_INCREMENT -- Unique ID for each contact,
  name varchar(255) NOT NULL -- Name of the contact person or company,
  belongs_in_group tinyint(1) NOT NULL DEFAULT 0 -- Indicates whether the contact belongs to the company group,
  created_at timestamp NULL DEFAULT NULL -- Timestamp of when the contact record was created,
  company_type enum('legal_entity','brand_name') DEFAULT NULL -- Type of company associated with the contact,
  PRIMARY KEY (id),
  UNIQUE KEY contacts_name_unique (name)
  ) COMMENT='Stores contact details for companies'

  CREATE TABLE invoices (
  id bigint(20) unsigned NOT NULL AUTO_INCREMENT -- Unique ID for each invoices,
  vendor_contact_id int(10) unsigned NOT NULL -- The contact ID of the vendor (payee) who issued the invoice,
  client_contact_id int(10) unsigned NOT NULL -- The contact ID of the client (payer) who is responsible for paying the invoice,
  issued_date date NOT NULL -- Date the invoice issued,
  total_amount double(8,2) NOT NULL DEFAULT 0.00 -- The invoice total value,
  paid_amount double(8,2) NOT NULL DEFAULT 0.00 -- The part of the total amount paid,
  due_amount double(8,2) NOT NULL DEFAULT 0.00 -- The remaining balance to be paid (total_amount-paid_amount),
  PRIMARY KEY (id)
  ) COMMENT='Stores information about issued invoices between to individuals, Vendor who is the payee and Client who is the payer';

  -- invoices.vendor_contact_id can be joined with contacts.id
  -- invoices.client_contact_id can be joined with contacts.id

**Comment by rishsriv** [comment]
Hi there, the model has no way of knowing if Microsoft is a client or a vendor based on the schema, and so will make assumptions to answer your question.

You should consider adding instructions in the prompt to give it more context.
