### ISSUE TITLE
How long can metadata.sql be?

### ISSUE THREAD

**Issue by rabum** [defog-ai/sqlcoder#78]
As I see in the user FAQs of defog there seems to be a pruning layer, does that mean I can dump however many schemas into metadata.sql and just run python inference.py -q "Question about the sample database goes here", irrelevant tables will be pruned without worrying about LLM's context length?
![image](https://github.com/defog-ai/sqlcoder/assets/58140899/905bccf7-11a2-4609-88ab-c1ace7454e8a)

**Comment by rishsriv** [comment]
Hi there, unfortunately not. Pruning is something that we provided in our hosted service, and is not yet available in the open-source version.
