### ISSUE TITLE
Facing error : 1146 (42S02)

### ISSUE THREAD

**Issue by bitwiseprat** [defog-ai/sqlcoder#79]
I was using Defog SQL Coder and had done a defog init previously for a different db ( lets call it db1 ) , but now I wanted to use a different db ( lets call it db2 ) and different tables , so : 
I removed the connection details stored in ( /home/ubuntu/.defog/connection.json) and reinstalled defog on python ( Python version 3.9.16 , Defog version 0.61.0). I then used defog init to provide the API key, database host, user etc. and generated a schema as well. 

But when I am querying something using the LLM , it gives the error : 1146 (42S02): Table 'db1.Customers' doesn't exist - while in the initialization I specified db2 but it is reverting back to db1 to look for that table that is in db2. 
I have tried changing the db name manually in the connection.json file but even after changing, it reverts back to the initial db that I was using before - db1 and not the new db2.

**Comment by rishsriv** [comment]
Hi there, the steps you describe _ought_ to have worked.

I suspect that you might have tables with capitalized characters in your new database. Could you check if that's the case?

If so, you might have to [follow these steps](https://stackoverflow.com/questions/20795947/mysql-table-name-not-working-in-uppercase) to make generated queries work. Defog uses the MySQL python connector under the hood, which does not play well with capitalized columns.

If it's a different issue, do let me know your API key and will be happy to look into it.

**Comment by bitwiseprat** [comment]
Hi, 

The tables were indeed capitalized but after changing them to lowercase and performing the same steps again I am getting the same error - the query being generated is for the incorrect db and the new one that I provided again during the init process is not being used.
