### ISSUE TITLE
how can i get the sql query  with result ?

### ISSUE THREAD

**Issue by prameela1610** [defog-ai/sqlcoder#8]
Great Thanks !!!!

If I give a meta data it is generating SQL query .it is fine but i need to get the SQL query results also .
how can i do this ???

**Comment by liujunleo** [comment]
> Great Thanks !!!!
> 
> If I give a meta data it is generating SQL query .it is fine but i need to get the SQL query results also . how can i do this ???

Undoubtedly, you need to execute this SQL in your database
