### ISSUE TITLE
sqlcoder launch seems failed

### ISSUE THREAD

**Issue by rabum** [defog-ai/sqlcoder#80]
I got this message after trying to launch, what could have caused it? 
![image](https://github.com/defog-ai/sqlcoder/assets/58140899/f943e69a-ed4c-4be9-a254-168651435a1c)

**Comment by rishsriv** [comment]
Hi there, it seems that the port used for SQLCoder (1235) is being used by another application. Try freeing the port and launching again?

**Comment by Bhagyesh-Shinde** [comment]
getting the same error
