### ISSUE TITLE
sqlcoder-7b-2 seems to be not good at calculating daily average

### ISSUE THREAD

**Issue by rabum** [defog-ai/sqlcoder#81]
Like I want it to write "sum(bal)/(date('2022-01-31')-date('2022-01-01')+1)" as daily average, but it just keeps writing "AVG(bal)", even though I told it in the question that you should do a division

**Comment by rishsriv** [comment]
Could you please share the full prompt you used? That will help us figure out what the issue is.

**Comment by rabum** [comment]
> Could you please share the full prompt you used? That will help us figure out what the issue is.

I used the default prompt in the project, the q is "Select the total daily average deposit balance from January 1, 2022 to January 31"
I have not found the effective prompt to make it write the intended answer

**Comment by rishsriv** [comment]
This is a reasonable answer for the question that you have asked. If you want it to be more specific, you can adapt the prompt with more specific instructions, by adding an instructions section to the prompt, [like here](https://huggingface.co/defog/sqlcoder-7b-2/discussions/10#65def872e587bda4fcf90b26) or align it to specific reference examples, like [here](https://github.com/defog-ai/sqlcoder/issues/48#issuecomment-1972612956)
