### ISSUE TITLE
what is the base-PT models of sqlcoder-7b-2？

### ISSUE THREAD

**Issue by OKC13** [defog-ai/sqlcoder#85]
what is the base-PT models of sqlcoder-7b-2？
codellama or starcode？or others？
Thanks a lot

**Comment by rishsriv** [comment]
CodeLlama-7B

**Comment by OKC13** [comment]
the starcode2 was released now，did you have this upgrade plan recently？

**Comment by chuangzhidan** [comment]
> CodeLlama

what about sqlcoder 70b alpha? llama3？
