### ISSUE TITLE
The model makes up columns if the column is not present

### ISSUE THREAD

**Issue by amand26** [defog-ai/sqlcoder#86]
Here is the schema:

CREATE TABLE person (
  id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT, -- A unique id for each person
  name VARCHAR(255) DEFAULT NULL, -- The full name of the person
  alias VARCHAR(255) DEFAULT NULL, -- Any known aliases or alternative names used by the person
  age INTEGER DEFAULT NULL, -- The age of the person
);

Query: Person with age > 20 from haryana
Output: SELECT p.name FROM person p WHERE p.age > 20 AND p.state = 'haryana';
The model made up a column state even if it is not present in the schema.

Using the 7B model.

Tried to update the instructions still the same issue.

**Comment by Saivignesh-05** [comment]
In issue #12, the authors specify that the schema used must be well-defined. Also, the model was tested only on definite queries (They have preprocessed data that have ambiguities) . Thus in these cases, like a usual LLM, it tends to hallucinate. 
What was the instruction used. Maybe try including the instruction not to hallucinate right in the beginning.
