### ISSUE TITLE
There are very long DDL in real situation may be 10000+ tokens, is it possible to support long input DDL?

### ISSUE THREAD

**Issue by ct-source** [defog-ai/sqlcoder#9]
Thank you for your awlsome work!

**Comment by lihaoyang-ruc** [comment]
Hi, the prevalence of lengthy DDL inputs is a common occurrence in real-world applications. To address this issue, an effective approach involves implementing a preprocessing module that extracts the most relevant tables and columns based on the natural language questions. This technique could significantly reduce the overall length of the input sequence, leading to improved efficiency. 

For further insight, you can explore our recent work, [CodeS](https://github.com/RUCKBReasoning/codes). In this work, we have successfully integrated a schema item filter, which plays a pivotal role in attaining the aforementioned objective. 😉

**Comment by nuaabuaa07** [comment]
> Hi, the prevalence of lengthy DDL inputs is a common occurrence in real-world applications. To address this issue, an effective approach involves implementing a preprocessing module that extracts the most relevant tables and columns based on the natural language questions. This technique could significantly reduce the overall length of the input sequence, leading to improved efficiency.
> 
> For further insight, you can explore our recent work, [CodeS](https://github.com/RUCKBReasoning/codes). In this work, we have successfully integrated a schema item filter, which plays a pivotal role in attaining the aforementioned objective. 😉

the Link you offer is closed!

**Comment by nuaabuaa07** [comment]
> > Hi, the prevalence of lengthy DDL inputs is a common occurrence in real-world applications. To address this issue, an effective approach involves implementing a preprocessing module that extracts the most relevant tables and columns based on the natural language questions. This technique could significantly reduce the overall length of the input sequence, leading to improved efficiency.
> > For further insight, you can explore our recent work, [CodeS](https://github.com/RUCKBReasoning/codes). In this work, we have successfully integrated a schema item filter, which plays a pivotal role in attaining the aforementioned objective. 😉
> 
> the Link you offer is closed!

I found code here. [https://github.com/defog-ai/sql-eval/blob/main/utils/pruning.py](url)
