### ISSUE TITLE
Compatibility with RAG-based framework

### ISSUE THREAD

**Issue by jis478** [defog-ai/sqlcoder#96]
Hi, thanks for the excellent work.  :)

I'm wondering if sqlcoder is compatible with similarity-based framework like langchain or vanna. For me, sqlcoder seems to refer to all the table information (inferred by `inference.py`) in the database but the above ones are basically RAG-frameworks so that they only retrieve and include relevant ones in the prompt. Does the each training example for sqlcoder only refer to specific relevant tables or to all the tables in the database?

**Comment by MohamadOHijazi** [comment]
You can use Ollama, and as you know Ollama is compatible with Vanna.ai
However, to the best of my knowledge, Ollama doesn't contain the latest sqlcoder 8 billion based on LLM3

**Comment by jis478** [comment]
@MohamadOHijazi My question was whether sql-coder is designed to work with relevant (retrieved) information, not about the compatibility with Ollama.

**Comment by chussboi96** [comment]
> @MohamadOHijazi My question was whether sql-coder is designed to work with relevant (retrieved) information, not about the compatibility with Ollama.

im stuck in a similar situation

**Comment by andyzhou1982** [comment]
specific relevant tables,you can find the information at ~/.defog/selected_tables.json
