### ISSUE TITLE
How to run SQLCoder 7b locally on Macbook Pro

### ISSUE THREAD

**Issue by debimishra89** [defog-ai/sqlcoder#97]
Hello,

I want to run and test SQLCoder-7b-2 (from huggingface) on my MackBook Pro. But it gets stuck forever.
Can you tell me what modifications i have to do to run it locally.

System report:
 
Model Name:	MacBook Pro
  Chip:	Apple M3 Pro
  Total Number of Cores:	12 (6 performance and 6 efficiency)
  Memory:	18 GB
  System Firmware Version:	10151.81.1
  OS Loader Version:	10151.81.1
  Serial Number (system):	F7K65R93WM
  Hardware UUID:	2D6F9FDF-D01A-56CB-BCD5-C0231954F3EB
  Provisioning UDID:	00006030-001445563482001C
  Activation Lock Status:	Disabled

**Comment by rupalg10** [comment]
@debimishra89 Did you find a resolution for this?
