### ISSUE TITLE
Limiting the response to the tables avb in the schema

### ISSUE THREAD

**Issue by MohamadOHijazi** [defog-ai/sqlcoder#99]
I have been performing multiple tests on the online Demo.  I have noticed that the model is ignoring instructions and generating results for prompts that contain Tables different than the schema provided.
I used the same schema in the demo and tested it multiple times however the model always generated Queries targeting tables that are not included in the schema provided.
Is their a way to address this issue without applying another model to classify if the prompt is relative to any of the tables AVB and if the prompt is referring to non-existing attribute?
an example is when asking ordering sales person by age. the model generated A DML the model didn't recognize that age is not avb in the sqldabase schema.
I attached an example image about this issue bellow.
![image](https://github.com/defog-ai/sqlcoder/assets/114419770/1e720cdc-4b5f-4b87-9304-a3b1fadd1ace)

**Comment by rishsriv** [comment]
Hi there, thank you for opening this issue and for including a replicable example. This seems to be a model regression that escaped our unit tests. we'll update the model weights to address this soon.

**Comment by MohamadOHijazi** [comment]
Thanks for your fast reply! And for your amazing project. 
After thoroughly searching it was the best open source LLM that I could find. 
To solve this issue I was thinking of adding a filtering layer that drops irrelevant queries. However, this will increase computational power needed and will remove the edge of this model.
Looking forward to try your updated model.
